[MIN-486] Fix bugs for admin dashboard.
minterest-finance/minterest-frontend pull request #108
Opened 2021-07-22 12:18 UTC by l-polina

**Description:**

Fix bugs for admin dashboard.

**Screenshots:**

Add some screenshots to illustrate your work.

2021-07-23 10:20 UTC, gavrilin-remote requested changes
Let's perform a bit refactoring around this changes.

2021-07-23 10:20 UTC, gavrilin-remote commented on src/actions/protocolAdminUpdates.ts
> +			const convertInsuranceFactor = convertToTokenValue(+newAmount / 100);
Let's make new utils function that will take value in arguments then will cast it to Number and divide to 100. 
100 - move to constants. Do not forget about type checking.
EG:
`const getTokenValue =(value: number || string) =>{
   if(typeof value === "number"){
   return convertToTokenValue(value / NUMERATOR)
   }else if(typeof value === "string" && !Number.isNaN(value)){
   return convertToTokenValue(Number(value) / NUMERATOR)
   }else {
   return 0;
   }
}`
This just a quick example, feel free to change this function as you want

2021-07-26 13:06 UTC, l-polina commented on src/actions/protocolAdminUpdates.ts
> +			const convertInsuranceFactor = convertToTokenValue(+newAmount / 100);
> Let's make new utils function that will take value in arguments then will cast it to Number and divide to 100.
> 100 - move to constants. Do not forget about type checking.
> EG:
> `const getTokenValue =(value: number || string) =>{ if(typeof value === "number"){ return convertToTokenValue(value / NUMERATOR) }else if(typeof value === "string" && !Number.isNaN(value)){ return convertToTokenValue(Number(value) / NUMERATOR) }else { return 0; } }`
> This just a quick example, feel free to change this function as you want

Made new utils function

2021-07-27 12:36 UTC, gavrilin-remote approved these changes

2021-07-27 12:38 UTC, merged